; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = espidf

# FORCE override board defaults
board_build.flash_size = 2MB
board_upload.flash_size = 2MB

# Nadpisz partitions
board_build.partitions = partitions_2MB.csv

# Wymuś przez sdkconfig
board_build.cmake_extra_args =
    -DCONFIG_ESPTOOLPY_FLASHSIZE_2MB=y
    -DCONFIG_ESPTOOLPY_FLASHSIZE=0x200000

build_flags =
    -DBOARD_HAS_PSRAM
    
monitor_speed = 115200